[build]
builder = "nixpacks"
buildCommand = "npm install --legacy-peer-deps && npm run build"

[deploy]
startCommand = "npx serve -s build"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "never"

# Diese Einstellung verhindert, dass Nixpacks npm ci verwendet
[phases.setup]
nixPkgsFile = "nodejs"
cmds = ["echo 'Skipping default npm ci'"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]